### ISSUE TITLE
visdom和CUDA参数

### ISSUE THREAD

**Issue by 131661** [chenxin-dlut/TransT#10]
问题1：运行run_tracker.py    为何debug参数不管设置数字为几   visdom里面只显示三幅图  而且俩幅图空白？
问题2：Attribute CUDA错误   basetracker.py 最后代码if cfg.CUDA:im_patch = im_patch.cuda()     cgf里面并无CUDA参数   直接将其注释改成im_patch = im_patch.cuda()可运行?

**Comment by chenxin-dlut** [comment]
十分感谢，因为我用pysot和got10k-toolkit测的结果，所以没注意到pytracking里测试可能的问题。
没错，将其注释改成im_patch = im_patch.cuda()即可，这样visdom显示也是正常的。

**Comment by Yifanpan1** [comment]
运行run_tracker.py 为何debug参数不管设置数字为几 visdom里面只显示三幅图 而且俩幅图空白？，我也遇到了问题1，请问如何解决呢
