### ISSUE TITLE
汉宁窗超参数

### ISSUE THREAD

**Issue by kongbia** [chenxin-dlut/TransT#11]
您好，请问汉宁窗的超参数是如何设置的，是像pysot那样在一个区间里搜索出来的吗？针对不同数据集都只用同一个超参数吗？

**Comment by chenxin-dlut** [comment]
我是在got-10k数据集上，从0.25到0.75的区间，每隔0.01测一次，从里边选的最好的一个：0.49。
论文里和github上面报的性能，所有数据集和所有模型都是用的0.49这个参数。
但是如果您针对每个不同的数据集去分别调参，那性能肯定会更好，只是会浪费一些时间。

**Comment by kongbia** [comment]
感谢您的回复，另外现在的代码在vot2020上只能输出矩形框，请问如何将alpha-refine嵌入进来呢？

**Comment by chenxin-dlut** [comment]
可以直接用alpha-refine的代码，然后把里面的tracker简单替换成transt就可以了，接口格式都是一致的

**Comment by kongbia** [comment]
明白了，感谢解答！
