### ISSUE TITLE
训练数据集的格式问题

### ISSUE THREAD

**Issue by yuyudiandian** [chenxin-dlut/TransT#12]
请问所用训练数据集的放置格式可以简单给一个模版样式么？

**Comment by chenxin-dlut** [comment]
![image](https://user-images.githubusercontent.com/56434931/114137075-4041ac80-993e-11eb-8c93-49160234a9a6.png)
这样可以看明白吗，如果不明白的话随时留言

**Comment by chenxin-dlut** [comment]
![1617949156(1)](https://user-images.githubusercontent.com/56434931/114137451-d4137880-993e-11eb-959a-5d5294197ced.png)
![1617949173(1)](https://user-images.githubusercontent.com/56434931/114137484-de357700-993e-11eb-903a-ebd5395082dc.png)
![1617949183(1)](https://user-images.githubusercontent.com/56434931/114137490-dfff3a80-993e-11eb-89fc-f052e4518b3b.png)
![1617949210(1)](https://user-images.githubusercontent.com/56434931/114137498-e1c8fe00-993e-11eb-92cc-d814d15652b3.png)

**Comment by yuyudiandian** [comment]
谢谢！这么看好像和stark的训练数据格式是一样的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxin-dlut/TransT] 训练数据集的格式问题 (#12)

**Comment by yuyudiandian** [comment]
现在又遇到了点新的问题 但是我现在只用了一个coco数据集进行训练 是不是做这些修改就可以？
![QQ图片20210409150141](https://user-images.githubusercontent.com/71555221/114141723-91ed3580-9944-11eb-8c4c-584f88b1be2d.png)
![QQ图片20210409150145](https://user-images.githubusercontent.com/71555221/114141732-93b6f900-9944-11eb-818d-79006a706d8e.png)

**Comment by chenxin-dlut** [comment]
> 现在又遇到了点新的问题 但是我现在只用了一个coco数据集进行训练 是不是做这些修改就可以？
> ![QQ图片20210409150141](https://user-images.githubusercontent.com/71555221/114141723-91ed3580-9944-11eb-8c4c-584f88b1be2d.png)
> ![QQ图片20210409150145](https://user-images.githubusercontent.com/71555221/114141732-93b6f900-9944-11eb-818d-79006a706d8e.png)

是的

**Comment by yuyudiandian** [comment]
想请问下有无参数改动可以降低训练显存的占用？两张1080ti的卡cuda out of memory。。尝试降低patch_size但是没有效果。

**Comment by chenxin-dlut** [comment]
> 想请问下有无参数改动可以降低训练显存的占用？两张1080ti的卡cuda out of memory。。尝试降低patch_size但是没有效果。

降低batch_size是不改动网络结构的情况下唯一降显存的方法；如果显存不够，说明batch_size还是不够小；1080ti有11G显存，两块的话应该可以做到14左右的batch_size，如果一块的话可以试试6、7、8，如果不行就再调小些

**Comment by yuyudiandian** [comment]
好的！谢谢解答！
