### ISSUE TITLE
GOT-10k训练问题

### ISSUE THREAD

**Issue by Nightwatch-Fox11** [chenxin-dlut/TransT#124]
您好，我是一名深度学习的初学者，有一些关于TransT在仅使用GOT-10k训练的问题想请教。

1. 请问您在仅使用GOT-10K时训练的参数是怎么设置的呢？epoch还是1k么？
2. 得到TransT_GOT.pth时的训练数据是完整的GOT-10k训练集么？
3. 在TransT/train_settings/transt/transt.py中进行如下修改时我的samples_per_epoch以及max_gap是否需要进行调整呢，还是就如下代码中设置即可？
`dataset_train = sampler.TransTSampler([got10k_train], [1],
                                          samples_per_epoch=1000 * settings.batch_size, max_gap=100,
                                          processing=data_processing_train)`

期待您的解答😀

**Comment by Nightwatch-Fox11** [comment]
还想请教一下您进行完整的GOT-10k训练所使用的GPU环境以及大致花费的时间

**Comment by Mango1218** [comment]
请问下你跑成功了吗
