### ISSUE TITLE
最后一层CFA的layer_norm

### ISSUE THREAD

**Issue by kongbia** [chenxin-dlut/TransT#13]
在featurefusion_network.py中，decoderCFA_layer中最后已经使用过了layer_norm，请问为什么还需要单独再加一层decoderCFA_norm再做一遍layer_norm呢？

**Comment by chenxin-dlut** [comment]
在DETR的实现中，就是这样两个layer_norm连着用的，所以这里我也没改。
但是理论上第一个normalization归一化之后就是均值为0，方差为1，再做第二个normalization其实跟没做的效果是一样的，这里两个layer_norm理论上是等价于一个normalization。DETR里之所以这么做应该是为了在forward_pre，forward_post两种情况下代码的简洁。

**Comment by kongbia** [comment]
感谢解答！
