### ISSUE TITLE
No matching checkpoint file found

### ISSUE THREAD

**Issue by wangqiang-66** [chenxin-dlut/TransT#15]
checkpoint文件在哪里下载

**Comment by chenxin-dlut** [comment]
![image](https://user-images.githubusercontent.com/56434931/114292896-76a93400-9ac4-11eb-924c-3d8624f9c972.png)
readme中这里有链接

**Comment by wangqiang-66** [comment]
thanks!

**Comment by wangqiang-66** [comment]
问题：你好，我想尝试训练，显示No matching checkpoint file found
我的理解：我将下载的transt.pth放在一个文件夹（save)里，然后将ltr/admin/local.py中的self.workspace_dir 换成了我自己的路径：
``self.workspace_dir = '/home/c506/wq/TransT/save'  
![image](https://user-images.githubusercontent.com/65331186/114295947-1c679d80-9adb-11eb-9e32-ac539605b244.png)
请问这样是错了吗，怎样修改呢？

**Comment by chenxin-dlut** [comment]
如果是从头训练，是不需要transt.pth的，你可以先把local.py中的必要路径指定好，不放transt.pth，看看能不能训练

**Comment by wangqiang-66** [comment]
您好，我将ltr/admin/local.py中的self.workspace_dir没有放入transt.pth，但是还是报错显示No matching checkpoint file found
疑问：如果从头训练只需要改local.py中的路径吗，其他py文件需要去改吗，比如loading.py和base_trainer.py
![image](https://user-images.githubusercontent.com/65331186/114296913-4c656f80-9ae0-11eb-95a4-8d07e6494246.png)
报错;
![image](https://user-images.githubusercontent.com/65331186/114297030-f04f1b00-9ae0-11eb-91a0-ef66e60f7cc4.png)
谢谢你了！

**Comment by chenxin-dlut** [comment]
首先，self.workspace_dir需要指定路径，您的图片中，指定了tensorboard的路径，但没有指定self.workspace_dir
其次，这个no matching found并不是错误，而且现在没有训练，之前没有存的模型，所以会出现这个提示，并不影响。
这个真正报错的原因是上边的valueerror，应该检查一下这部分错误，看上去和数据集有关

**Comment by wangqiang-66** [comment]
您好，按照您的回答我纠正了下，我只用了got-10k和lasot作为训练集，然后报了两个value error。尝试使用一个数据集也是显示一样的错误
路径配置：
![image](https://user-images.githubusercontent.com/65331186/114303777-5b5d1980-9b02-11eb-9c71-3e4b5c03cbdc.png)
value error
![image](https://user-images.githubusercontent.com/65331186/114303417-9bbb9800-9b00-11eb-8043-b3ea4e8b1ee2.png)
![image](https://user-images.githubusercontent.com/65331186/114303434-a8d88700-9b00-11eb-91e3-a88f7d13185b.png)
我百度了好像是数据集没有load的错误
疑问;如果您知道我可能会出错的地方在在哪里能劳烦您指出下吗？目标跟踪·小白，如果打扰到您可不必回复。

**Comment by chenxin-dlut** [comment]
改数据集的话，tranining_setting/transt.py里没有用的的数据集要注释掉

**Comment by chenxin-dlut** [comment]
参考这个： https://github.com/chenxin-dlut/TransT/issues/12

**Comment by wangqiang-66** [comment]
谢谢您的解答，终于跑起来了，感谢！

**Comment by wsasdsda** [comment]
我现在遇到了同样的问题，方便说一下具体怎么解决的吗？

**Comment by Nuyoah1018** [comment]
> 您好，按照您的回答我纠正了下，我只用了got-10k和lasot作为训练集，然后报了两个value error。尝试使用一个数据集也是显示一样的错误 路径配置： ![image](https://user-images.githubusercontent.com/65331186/114303777-5b5d1980-9b02-11eb-9c71-3e4b5c03cbdc.png) value error ![image](https://user-images.githubusercontent.com/65331186/114303417-9bbb9800-9b00-11eb-8043-b3ea4e8b1ee2.png) ![image](https://user-images.githubusercontent.com/65331186/114303434-a8d88700-9b00-11eb-91e3-a88f7d13185b.png) 我百度了好像是数据集没有load的错误 疑问;如果您知道我可能会出错的地方在在哪里能劳烦您指出下吗？目标跟踪·小白，如果打扰到您可不必回复。

你好，遇到了No matching checkpoint file found同样的问题，能指导一下具体怎么修改的吗

**Comment by maxinmine** [comment]
您好，想问一下代码卡在no matching checkpoint之后就不动了，也没有报错，想问一下怎么解决呢？

![Image](https://github.com/user-attachments/assets/b6377f58-f74b-48e4-9557-0513e29c73bd)
