### ISSUE TITLE
eval.py

### ISSUE THREAD

**Issue by wangqiang-66** [chenxin-dlut/TransT#16]
你好，eval OTB2015时显示没有OTB2015.JSON文件，需要在results文件夹放入json文件?谢谢！
![image](https://user-images.githubusercontent.com/65331186/114661956-7611d700-9d2a-11eb-8759-78755a8d32b8.png)
![image](https://user-images.githubusercontent.com/65331186/114661999-8b870100-9d2a-11eb-9978-374d4c8dff7a.png)

**Comment by chenxin-dlut** [comment]
可以在这里下载json文件:https://github.com/STVIR/pysot
也可以用got-10k的toolkit来eval，无需json文件：https://github.com/got-10k/toolkit

**Comment by chenxin-dlut** [comment]
json文件要放在数据集里，并非results里

**Comment by wangqiang-66** [comment]
我的步骤：
1.训练自己的模型
2.在OTB2015数据集测试自己的模型生成results文件夹中包括OTB2015(.txt)文件
3.我有疑问:在eval环节报错显示没有OTB2015.json文件，我尝试将OTB2015.json文件放入results报了相同的error,
评估模型只需要这行指令无需做其他添加或者修改路径吗？谢谢！
 python pysot_toolkit/eval.py --tracker_path results --dataset OTB2015 --num 1 --tracker_prefix 'transt'
![image](https://user-images.githubusercontent.com/65331186/114669039-09033f00-9d34-11eb-8a59-412a9bcd32df.png)

**Comment by chenxin-dlut** [comment]
json文件是要放进OTB数据集里的哈，不是放进results里。
放在这张图片里显示的那个路径中
![image](https://user-images.githubusercontent.com/56434931/114673200-8466ef80-9d38-11eb-8085-598e2a193548.png)

**Comment by wangqiang-66** [comment]
谢谢你，已解决，

**Comment by LeungWaiHo** [comment]
> 谢谢你，已解决，
请问testing_dataset这个路径是怎么生成的？
