### ISSUE TITLE
论文有一处疑惑

### ISSUE THREAD

**Issue by YangChen-UCAS** [chenxin-dlut/TransT#17]
在related work的第一节Visual object tracking中，您提到correlation有两个问题.第一个是不能充分利用全局信息，我能理解。第二个问题，经过correlation,语义信息会有丢失，请问这作何理解？您能解答一下吗？

**Comment by chenxin-dlut** [comment]
是这样，correlation是对两张特征图的比较，它计算出来的只能代表每个位置的相似度，不是严格意义上的特征，是没有语义信息的，它的含义仅仅是相似度
