### ISSUE TITLE
根据要求配置好后，为什么我一运行python run_training.py transt transt 就会卡死呢？

### ISSUE THREAD

**Issue by BaBaWen** [chenxin-dlut/TransT#18]
如题！ 我尝试用windows 和Ubuntu都试了下，在我一切都配置好后，Windows任务管理器显示，在我运行后，内存狂飙我是16G内存，然后飙到16G满了后，电脑开始卡死。Ubuntu也是同样情况,请问这是什么情况呢？

**Comment by chenxin-dlut** [comment]
你好，我的机器是64G内存，并没有出现内存不够的情况，你的问题我不确定是出在哪里。但是你可以试一下减少batchsize等操作使读取的图片少一些

**Comment by BaBaWen** [comment]
我看到您在另一个issue里面，说如果单张1080ti，batchsize设置6.7.8，明天再加两个内存条到32G在尝试下，我尝试设置为4仍然不能训练，小的batchsize会使训练不能收敛，我感觉在设置更小的话，对于3060 12G显存，就无法进行训练了，或者说根本不会收敛。

**Comment by BaBaWen** [comment]
不知道除了batchsize，还有没有其他方式可以减小参数。

**Comment by chenxin-dlut** [comment]
减少每个epoch的训练次数，同时增大总的epoch数。
另外，也有可能是没用上GPU导致中间计算都存在内存而不是显存

**Comment by BaBaWen** [comment]
刚刚看了任务管理器，发现GPU 利用率0%，貌似没有用到GPU，我是单卡3060 12G，请问是否是我将 settings.multi_gpu = False，导致的呢？ 请问关于GPU使用具体代码在哪里呢？

**Comment by chenxin-dlut** [comment]
默认就是用GPU的，你可以试一下打开multi_GPU，单卡也没关系

**Comment by BaBaWen** [comment]
打开多卡gpu，同时我也测试了在pytorch 和tensorflow我的GPU都是可用的，仍然是加载不到GPU中，持续是0%，请问这种情况应该怎么办，问题有点多，如果打扰到您请多见谅~！

**Comment by BaBaWen** [comment]
同时我测试了pytracking/run_webcam.py，同样也是可用的，ltr/run_traing.py 就会卡死

**Comment by chenxin-dlut** [comment]
刚才看了一下，我用服务器训练时内存占用有40G，也许确实是读数据的时候内存不足，加内存试试吧

**Comment by BaBaWen** [comment]
好的，明天再加两根内存组个32g试试，还有个问题，想请问下，您在训练时候，采用四个数据集，我现在仅仅使用coco进行训练，那么读取数据时候应该会比40G小吧

**Comment by chenxin-dlut** [comment]
如果每个epoch读取图片数量一致，减少数据集的种类理论上不会减少内存占用

**Comment by BaBaWen** [comment]
好的明白了，我明天加内存，同时减小batchsize和图片数量试试，非常感谢您周末还解答我的问题！！

**Comment by chenxin-dlut** [comment]
忽然想起来，30系显卡不支持cuda11以下版本，不要按照我的安装教程安装cuda10，要安装cuda11以上的版本

**Comment by BaBaWen** [comment]
我是安装的cuda11.1，就是因为不支持cuda10以下版本，导致在pytracking里面的大多数采用了PrPool的，都不能正确导入，您的TransT并没有采用，所以我才能运行，我还没有加内存尝试，但是尝试了lwl，出现问题和您的这个是一样的，也是内存疯长，就不行了，我怀疑是代码里某一个问题。

**Comment by swrdZWJ** [comment]
您好，我也遇到了同样的问题，我电脑是32G的内存也不够用，请问解决了吗 @BaBaWen 感谢～ @chenxin-dlut

**Comment by cheehowH** [comment]
> 我是安装的cuda11.1，就是因为不支持cuda10以下版本，导致在pytracking里面的大多数采用了PrPool的，都不能正确导入，您的TransT并没有采用，所以我才能运行，我还没有加内存尝试，但是尝试了lwl，出现问题和您的这个是一样的，也是内存疯长，就不行了，我怀疑是代码里某一个问题。

请问您解决了吗，现在也遇到了这个问题
