### ISSUE TITLE
N× Feature Fusion Layer的具体架构

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#20]
您好！
在您的论文看到Feature Fusion Network的N× Feature Fusion Layer是一种统一表述，请问例如4× Feature Fusion Layer的架构图是怎样的呢？

**Comment by chenxin-dlut** [comment]
就是论文里的结构图的虚线框中的结构循环N次，前边一个循环的输出作为后边一个循环的输入，细节建议看一下代码

**Comment by ANdong-star** [comment]
> 就是论文里的结构图的虚线框中的结构循环N次，前边一个循环的输出作为后边一个循环的输入，细节建议看一下代码

好的谢谢！ 只是看到虚线框内是两个输入一个输出，前后连起来的话输入输出数量不一致的话不知道要做什么处理，具体细节我看一下代码。

**Comment by chenxin-dlut** [comment]
> > 就是论文里的结构图的虚线框中的结构循环N次，前边一个循环的输出作为后边一个循环的输入，细节建议看一下代码
> 
> 好的谢谢！ 只是看到虚线框内是两个输入一个输出，前后连起来的话输入输出数量不一致的话不知道要做什么处理，具体细节我看一下代码。

重复的部分是灰色虚线框，是有两个输出的

**Comment by ANdong-star** [comment]
> > > 就是论文里的结构图的虚线框中的结构循环N次，前边一个循环的输出作为后边一个循环的输入，细节建议看一下代码
> > 
> > 
> > 好的谢谢！ 只是看到虚线框内是两个输入一个输出，前后连起来的话输入输出数量不一致的话不知道要做什么处理，具体细节我看一下代码。
> 
> 重复的部分是灰色虚线框，是有两个输出的

原来如此，明白了！十分感谢！
