### ISSUE TITLE
Evaluation on GOT10k dataset

### ISSUE THREAD

**Issue by GehenHe** [chenxin-dlut/TransT#21]
我试着在GOT10k数据集上评测模型，但是在pysot_toolkit/eval.py中没有该数据集的评测代码。
想请教下在现有代码的基础上，如何评测模型在GOT10k上的性能？

万分感谢！

**Comment by chenxin-dlut** [comment]
got10k要上传官网评测

**Comment by GehenHe** [comment]
好的，感谢回复
