### ISSUE TITLE
lasot数据集test

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#24]
您好！
请问lasot数据集运行test.py文件的时候dataset_root路径是定义哪里呢？没有看到分出来的test文件。感谢！

**Comment by ANdong-star** [comment]
看了一下json文件，是要手动把一部分文件分出来么？还是有分隔文件的代码呢？

**Comment by chenxin-dlut** [comment]
用pysot的test.py测lasot的话，dataset_root指向LaSOTBenchmark文件夹，这个文件夹下面需要直接是airplane-9这种视频序列，而不能是airplane/airplane-9这样。
不过也可以通过改json文件来自己定义存储形式，只要保持json文件与自己的存储形式一致，就都是没问题的。

**Comment by ANdong-star** [comment]
> 用pysot的test.py测lasot的话，dataset_root指向LaSOTBenchmark文件夹，这个文件夹下面需要直接是airplane-9这种视频序列，而不能是airplane/airplane-9这样。
> 不过也可以通过改json文件来自己定义存储形式，只要保持json文件与自己的存储形式一致，就都是没问题的。
好的 谢谢！

**Comment by ANdong-star** [comment]
> 用pysot的test.py测lasot的话，dataset_root指向LaSOTBenchmark文件夹，这个文件夹下面需要直接是airplane-9这种视频序列，而不能是airplane/airplane-9这样。
> 不过也可以通过改json文件来自己定义存储形式，只要保持json文件与自己的存储形式一致，就都是没问题的。

**Comment by ANdong-star** [comment]
> 用pysot的test.py测lasot的话，dataset_root指向LaSOTBenchmark文件夹，这个文件夹下面需要直接是airplane-9这种视频序列，而不能是airplane/airplane-9这样。
> 不过也可以通过改json文件来自己定义存储形式，只要保持json文件与自己的存储形式一致，就都是没问题的。

好的 谢谢！
