### ISSUE TITLE
pytracking测试

### ISSUE THREAD

**Issue by 131661** [chenxin-dlut/TransT#25]
您好这边会将pytracking测试时debug参数无论改多少visdom只显示一张跟踪图的问题解决然后上传到github吧，本想自己解决但是能力有限改了几天都不行。

**Comment by chenxin-dlut** [comment]
我在用的时候没有存在这个问题，debug设为1，显示是正常的呀

**Comment by Yifanpan1** [comment]
我也遇到了同样的问题，请问如何解决啊
