### ISSUE TITLE
关于论文中N 1--4可视化

### ISSUE THREAD

**Issue by BaBaWen** [chenxin-dlut/TransT#27]
您好，请问下论文中的可视化是怎么实现的？我在代码featurefusion_network.py  可以找到每一层得到的src1 src2 ，没有找到相关的可视化代码。

**Comment by chenxin-dlut** [comment]
这部分代码这个repo里没有提供，如果你看multihead_attention层的返回数据的话，你会发现attention层会同时返回计算结果和attention map，只需要把attention map拿出来用plt等工具可视化一下就好

**Comment by BaBaWen** [comment]
您好，我看了下代码如下，有几个问题：
'''src12= self.multihead_attn1(query=self.with_pos_embed(src1, pos_src1),
                                   key=self.with_pos_embed(src2, pos_src2),
                                   value=src2, attn_mask=src2_mask,
                                   key_padding_mask=src2_key_padding_mask)[0]'''
'''    if need_weights:
        # average attention weights over heads
        attn_output_weights = attn_output_weights.view(bsz, num_heads, tgt_len, src_len)
        return attn_output, attn_output_weights.sum(dim=1) / num_heads '''
1.我debug发现，确实返回了两个，一个是attn_output,一个是attn_output_weights，按理说返回给了src12，但是在数据中却没有找到attn_output_weights呢？
2.src12[256,1,256],src22[1024,1,256],他们的数据是这样的，在四次融合，第一次得到的src1,src2各自跟前面的一样，维数不匹配是如何可视化的呢？
期待您的回复！

**Comment by chenxin-dlut** [comment]
attention层后面有个[0]，src12只接收了attn_output，想要得到attn_output_weights把这块代码改一下。
[N1,1,N2]代表N1个向量分别对N2个向量的关注，取出N1其中的一个，把N2 reshape回2D的就可以了

**Comment by BaBaWen** [comment]
您好，为啥我画出来跟您不一样？
![myplot3](https://user-images.githubusercontent.com/72786365/116077947-a06b7900-a6c8-11eb-8e81-2da4749b71dc.png)
![myplot](https://user-images.githubusercontent.com/72786365/116077964-a3ff0000-a6c8-11eb-8c78-16f834018347.png)
![myplot1](https://user-images.githubusercontent.com/72786365/116077975-a6f9f080-a6c8-11eb-8695-cf81780f15ee.png)
这里我放了N=1时候的样本图像对应的ECA和CFA图像，您的那种是怎么画的呢？CFA的注意力图像画出来是长方形居然。

**Comment by chenxin-dlut** [comment]
参考 https://github.com/chenxin-dlut/TransT/issues/29
