### ISSUE TITLE
trackingnet训练出现 KeyError: 'Nf1aqv5Fg5o_0'

### ISSUE THREAD

**Issue by kongbia** [chenxin-dlut/TransT#28]
您好，我发现在训练trackingnet的时候会出现KeyError: 'Nf1aqv5Fg5o_0'，参照原始的pytracking [issue156](https://github.com/visionml/pytracking/issues/156) 似乎需要adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file

**Comment by chenxin-dlut** [comment]
你好，确实是这样的，我之前不小心把这一行删掉了

**Comment by ANdong-star** [comment]
> 您好，我发现在训练trackingnet的时候会出现KeyError: 'Nf1aqv5Fg5o_0'，参照原始的pytracking [issue156](https://github.com/visionml/pytracking/issues/156) 似乎需要adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file

您好！想问您一下，我在trackingnet_classmap.txt中加入Nf1aqv5Fg5o_0 airplane后，一直报错IndexError: list index out of range。想问一下您遇到过这种情况么？ 谢谢！

**Comment by kongbia** [comment]
> > 您好，我发现在训练trackingnet的时候会出现KeyError: 'Nf1aqv5Fg5o_0'，参照原始的pytracking [issue156](https://github.com/visionml/pytracking/issues/156) 似乎需要adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file
> 
> 您好！想问您一下，我在trackingnet_classmap.txt中加入Nf1aqv5Fg5o_0 airplane后，一直报错IndexError: list index out of range。想问一下您遇到过这种情况么？ 谢谢！

应该是中间那个空格间隔的问题，建议那个空格可以从其他行复制过来

**Comment by ANdong-star** [comment]
> > > 您好，我发现在训练trackingnet的时候会出现KeyError: 'Nf1aqv5Fg5o_0'，参照原始的pytracking [issue156](https://github.com/visionml/pytracking/issues/156) 似乎需要adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file
> > 
> > 
> > 您好！想问您一下，我在trackingnet_classmap.txt中加入Nf1aqv5Fg5o_0 airplane后，一直报错IndexError: list index out of range。想问一下您遇到过这种情况么？ 谢谢！
> 
> 应该是中间那个空格间隔的问题，建议那个空格可以从其他行复制过来
解决了，非常感谢！
