### ISSUE TITLE
How to draw attention map in your paper?

### ISSUE THREAD

**Issue by black12357** [chenxin-dlut/TransT#29]
thank you for your great work? but I wonder: could you share the code for visualizing attention maps in your paper?
I'm looking forward from you.

**Comment by chenxin-dlut** [comment]
![image](https://user-images.githubusercontent.com/56434931/117396699-1a9fc700-af2d-11eb-8ae5-8fe95774d987.png)
![image](https://user-images.githubusercontent.com/56434931/117396735-2c816a00-af2d-11eb-8673-887e36433912.png)

**Comment by bigboomclap** [comment]
c_weight22是如何生成的，c_weight22适合src22相同吗？
