### ISSUE TITLE
How to train on multi gpus?

### ISSUE THREAD

**Issue by tominute** [chenxin-dlut/TransT#3]
Nice work! I cannot find related codes about using multi gpus. How can I train TransT on multi gpus?

**Comment by chenxin-dlut** [comment]
Thank you. 
You can perform multi-gpu training by specifying
 `settings.multi_gpu = true`
in TransT/ltr/train_settings/transt/transt.py   line 17

**Comment by tominute** [comment]
I have found this setting but it seems it doesn't work. There may be a lack of codes in multigpu.py.

**Comment by chenxin-dlut** [comment]
We did not have this problem in debugging, you can try to add 
`CUDA_VISIBLE_DEVICES=0,1 ` 0,1 are GPU numbers 
before the training command to specify the GPUs used

**Comment by tominute** [comment]
I've found the problem. It works. Thanks

**Comment by ShoaibSajid** [comment]
> I've found the problem. It works. Thanks

What was the issue?
