### ISSUE TITLE
About the inference speed. 

### ISSUE THREAD

**Issue by llpspark** [chenxin-dlut/TransT#31]
hello, I have test the model(trans.pth) in GOT10k LaSOTBenchmark, but I got the lower inference speed(13FPS) than the paper had mentioned(50FPS).  On other hand the speed is unstable between different test instance, also same instance but different executing time.  PS: Intel(R) Xeon(R) CPU E5-2640; GPU: 1080TI .
![image](https://user-images.githubusercontent.com/20918669/117254879-92151e00-ae7b-11eb-836a-193a40087aef.png)

**Comment by chenxin-dlut** [comment]
Please check whether other programs occupy the computing resources. The following are my test results on 2080ti. The speed is normal.
![image](https://user-images.githubusercontent.com/56434931/117396602-d90f1c00-af2c-11eb-9c82-005178351301.png)
