### ISSUE TITLE
关于缩短训练时间的参数设置

### ISSUE THREAD

**Issue by RaymondCover** [chenxin-dlut/TransT#32]
能否提供训练500个epoch时的训练设置TransT/ltr/train_settings/transt/transt.py，（学习率，weight_decay等参数）。我发现我自己修改的使用500个epoch，学习率变为原来的两倍，然后在第250个epoch进行学习率衰减的策略性能下降的比较多,不清楚是哪方面原因造成的，谢谢。

**Comment by chenxin-dlut** [comment]
学习率，weight_decay等参数 与 之前一致即可， 请问下降多少呢?

**Comment by RaymondCover** [comment]
您好，我在RGBT234数据集的可见光模态做了实验，结果如下：
![Uploading image.png…]()
transt-N2和transt-500分别是使用1000个和500个epoch训练的模型，发现性能有较大差距，我看到您在其他问题回答提到学习率变为原来两倍的训练策略，weight_decay参数是保持不变吗？

**Comment by chenxin-dlut** [comment]
你好，大约1个点的差距其实是正常的差距，毕竟少训了一半时间；关于学习率，我最近的经验学习率是否调为两倍性能差距也不大，weight_decay保持不变即可。

**Comment by RaymondCover** [comment]
好的，非常感谢您的帮助，谢谢。
