### ISSUE TITLE
Results on TNL2K dataset

### ISSUE THREAD

**Issue by wangxiao5791509** [chenxin-dlut/TransT#33]
Hi, thanks for sharing your code. We release a new dataset termed TNL2K, and also test your tracker on our dataset. The overall performance looks good. Would you please add the [results ](https://drive.google.com/file/d/11oZqL8CtgDa9843NFaG7VVO5-7dn8xh-/view?usp=sharing) on this github? Thanks. 

![image](https://user-images.githubusercontent.com/12805786/117913540-1a7c3e80-b314-11eb-9e9d-266777aef1c8.png)

**Comment by chenxin-dlut** [comment]
thanks, nice work! I will add the results.
