### ISSUE TITLE
Also about the inference speed

### ISSUE THREAD

**Issue by DonDominic** [chenxin-dlut/TransT#36]
hello, I have test the model(trans.pth) in GOT10k-test, but I also got the lower inference speed (around 30 fps) than the paper had mentioned(47 fps). Need to note that I use the same GPU: RTX-TITAN with you and I'm sure no other programs occupy the computing resources. 
Will the inference speed be affected by other factors?
PS my CPU: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
![Snipaste_2021-05-19_22-01-19](https://user-images.githubusercontent.com/34258813/118834174-9b2ed200-b8f4-11eb-96bd-f7be49f7e112.png)

**Comment by chenxin-dlut** [comment]
Hello, I have just tested the code and the speed is normal (about 47fps) on my machine. 
Could you test how much time each part of the program takes？ A forward propagation of the model is about 20ms on my machine. Could you test the time of a forward propagation of the model on your machine?

**Comment by DonDominic** [comment]
I have just tested the time of forward propagation of the model with different pytorch version
pytorch 1.8.0 corresponds to 25ms
pytorch 1.7.0 corresponds to 29ms
and pytorch 1.5.1 corresponds to 26ms (under ur installation guideline)
PS my cuda version is 10.2 and cudnn: v8.1.1
![pytorch](https://user-images.githubusercontent.com/34258813/118909105-1627d500-b955-11eb-8381-295daa36a124.png)
<img width="574" alt="Snipaste_2021-05-20_09-47-37" src="https://user-images.githubusercontent.com/34258813/118909163-2b9cff00-b955-11eb-8366-8e60ea68b330.png">

**Comment by chenxin-dlut** [comment]
Hello,  I tested the code on other machines(2080Ti) and found that there is no problem with the speed, about 46fps on got10k and 53 fps on LaSOT. I'm sorry I can't solve your problem for now.

**Comment by DonDominic** [comment]
okk, thx for your patience!
