### ISSUE TITLE
关于attention map的问题

### ISSUE THREAD

**Issue by sunmengyu11** [chenxin-dlut/TransT#37]
作者你好，我看了之前您回答其他人关于如何画attention map的问题，我尝试把代码加了进去`        
               src12, attn_map1 = self.self_attn1(q1, k1, value=src1, attn_mask=src1_mask,
                               key_padding_mask=src1_key_padding_mask)
        src22, attn_map2 = self.self_attn2(q2, k2, value=src2, attn_mask=src2_mask,
                               key_padding_mask=src2_key_padding_mask)
attn_map1 = attn_map1.cpu().data.numpy()[0].reshape(256,16,16)[0]
        attn_map2 = attn_map2.cpu().data.numpy()[0].reshape(1024,32,32)[0]
 
        def pltshow(pred_map, name):
           import matplotlib.pyplot as plt
           plt.figure(2)
           pred_frame = plt.gca()
           plt.imshow(pred_map, 'jet')
           pred_frame.axes.get_yaxis().set_visible(False)
           pred_frame.axes.get_xaxis().set_visible(False)
           pred_frame.spines['top'].set_visible(False)
           pred_frame.spines['bottom'].set_visible(False)
           pred_frame.spines['left'].set_visible(False)
           pred_frame.spines['right'].set_visible(False)
           pred_name = '/home/sun/桌面/TransT/heatmap/' + name + '.png'
           plt.savefig(pred_name, bbox_inches='tight', pad_inches=0, dpi=150)
           plt.close(2)

        pltshow(attn_map1, 'aaa')
        pltshow(attn_map2, 'bbb')`
        src12, attn_map11 = self.multihead_attn1(query=self.with_pos_embed(src1, pos_src1),
                                   key=self.with_pos_embed(src2, pos_src2),
                                   value=src2, attn_mask=src2_mask,
                                   key_padding_mask=src2_key_padding_mask)
        src22, attn_map12 = self.multihead_attn2(query=self.with_pos_embed(src2, pos_src2),
                                   key=self.with_pos_embed(src1, pos_src1),
                                   value=src1, attn_mask=src1_mask,
                                   key_padding_mask=src1_key_padding_mask)
        attn_map11 = attn_map11.cpu().data.numpy()[0].reshape(256,32,32)[0]
        attn_map12 = attn_map12.cpu().data.numpy()[0].reshape(1024,16,16)[0]
        pltshow(attn_map11, 'ccc')
        pltshow(attn_map12, 'ddd') 
我加进去之后，发现第二个图bbb一直在左上角有很高的响应值，无论什么序列，还有第四副图ddd，他的高响应值都在四个角上，和论文中的不一样，我想问下为什么会这样，是我的代码有问题吗？期待您的回复！

**Comment by chenxin-dlut** [comment]
可以发以下你画得结果吗

**Comment by sunmengyu11** [comment]
![aaa1](https://user-images.githubusercontent.com/84486878/119096314-03d99400-ba46-11eb-8259-e22bb14cae08.png)
![aaa2](https://user-images.githubusercontent.com/84486878/119096346-0fc55600-ba46-11eb-874e-ebd5881f7d85.png)
![aaa3](https://user-images.githubusercontent.com/84486878/119096352-118f1980-ba46-11eb-9495-779ed1067909.png)
![aaa4](https://user-images.githubusercontent.com/84486878/119096360-13f17380-ba46-11eb-8907-6f84b460e453.png)
这四张为aaa，分别作了1-4次循环的结果（我理解的是这个是template的self-attention的结果）
![bbb1](https://user-images.githubusercontent.com/84486878/119096486-3edbc780-ba46-11eb-90ae-562ada8a1c6c.png)
![bbb2](https://user-images.githubusercontent.com/84486878/119096491-40a58b00-ba46-11eb-812f-40e38b604139.png)
![bbb3](https://user-images.githubusercontent.com/84486878/119096497-426f4e80-ba46-11eb-827e-1a697644507d.png)
![bbb4](https://user-images.githubusercontent.com/84486878/119096509-44391200-ba46-11eb-8f30-951095bf0877.png)
这四张为bbb，分别作了1-4次循环的结果（我理解的是这个是search region的self-attention的结果）
![ccc1](https://user-images.githubusercontent.com/84486878/119096561-5450f180-ba46-11eb-8d49-0cda8166a280.png)
![ccc2](https://user-images.githubusercontent.com/84486878/119096569-56b34b80-ba46-11eb-9ecf-307f2a162d67.png)
![ccc3](https://user-images.githubusercontent.com/84486878/119096583-5a46d280-ba46-11eb-9305-1b4b352a3275.png)
![ccc4](https://user-images.githubusercontent.com/84486878/119096590-5c109600-ba46-11eb-8194-0c00c188fcf3.png)
这四张为ccc，分别作了1-4次循环的结果（我理解的是这个是template的cross-attention的结果）
![ddd1](https://user-images.githubusercontent.com/84486878/119096671-721e5680-ba46-11eb-8cc5-5a5df58c1f86.png)
![ddd2](https://user-images.githubusercontent.com/84486878/119096675-73e81a00-ba46-11eb-8a75-d5f332483058.png)
![ddd3](https://user-images.githubusercontent.com/84486878/119096684-75b1dd80-ba46-11eb-92ca-1df16d98301b.png)
![ddd4](https://user-images.githubusercontent.com/84486878/119096689-76e30a80-ba46-11eb-96a6-6bc4544c88ff.png)
这四张为ddd，分别作了1-4次循环的结果（我理解的是这个是search region的cross-attention的结果）

**Comment by sunmengyu11** [comment]
测试的序列为vot中ant1的序列，就是论文中放attention map结果的序列，这几张图是和论文中同一图片下的结果，也就是第5帧的结果

**Comment by chenxin-dlut** [comment]
注意到你取的都是reshape之后的第0个，即左上角特征点对其他特征点的attention map，因此会出现这样的情况。
我在论文中放的图，对于搜索区域，取的是置信度分数最高的点，对于模板，取得是中间的点。
就是说，attn_map2 = attn_map2.cpu().data.numpy()[0].reshape(1024,32,32)[0] 这里的[0]要改成置信度最高的那个点的index

**Comment by sunmengyu11** [comment]
好的，谢谢，我这就是尝试下

**Comment by xiaolin13** [comment]
> 注意到你取的都是reshape之后的第0个，即左上角特征点对其他特征点的attention map，因此会出现这样的情况。 我在论文中放的图，对于搜索区域，取的是置信度分数最高的点，对于模板，取得是中间的点。 就是说，attn_map2 = attn_map2.cpu().data.numpy()[0].reshape(1024,32,32)[0] 这里的[0]要改成置信度最高的那个点的index

你好，这个取置信度最高的点的index的代码能提供一下吗

**Comment by bigboomclap** [comment]
> 注意到你取的都是reshape之后的第0个，即左上角特征点对其他特征点的attention map，因此会出现这样的情况。 我在论文中放的图，对于搜索区域，取的是置信度分数最高的点，对于模板，取得是中间的点。 就是说，attn_map2 = attn_map2.cpu().data.numpy()[0].reshape(1024,32,32)[0] 这里的[0]要改成置信度最高的那个点的index

请问怎么确定置信度最高的那个点的index呢？

**Comment by bigboomclap** [comment]
> 注意到你取的都是reshape之后的第0个，即左上角特征点对其他特征点的attention map，因此会出现这样的情况。 我在论文中放的图，对于搜索区域，取的是置信度分数最高的点，对于模板，取得是中间的点。 就是说，attn_map2 = attn_map2.cpu().data.numpy()[0].reshape(1024,32,32)[0] 这里的[0]要改成置信度最高的那个点的index

是选取32，32中加权平均的最大值吗？

**Comment by bobo-liang** [comment]
> 

请问您解决了吗
