### ISSUE TITLE
transt backbone关于BackboneBase这个类起什么作用，以及更改backbone报错

### ISSUE THREAD

**Issue by fangliang-123** [chenxin-dlut/TransT#39]
![image](https://user-images.githubusercontent.com/82500188/119251327-a1fd6380-bbd8-11eb-962c-e4e9bc8fbfee.png)
![image](https://user-images.githubusercontent.com/82500188/119251347-af1a5280-bbd8-11eb-995a-7381bce5db02.png)
1.Backbone base作用是什么，没太看懂
2.换了backbone后显示tensor没有items这个attribute
谢谢！

**Comment by chenxin-dlut** [comment]
1. tensor base是将tensor转化为NestedTensor格式
2. 源码的xs是字典,你换了之后的xs是tensor.

**Comment by fangliang-123** [comment]
thanks！
