### ISSUE TITLE
Influence of fusion layers

### ISSUE THREAD

**Issue by YaqiLYU** [chenxin-dlut/TransT#4]
Nice work！Very concise  framework. I like it!
1. How does the number of fusion layer influence the performance of TransT? Any experiment on N=[1, 2, 3]?
2. TransT does not need any online update, really? Will online update boost performance?
3. How to get HxW prediction from fusion vector? Directly reshape the output of MLP?

I want to transform TransT into a lightweight version for mobile application, any suggestion? Thanks a lot.

**Comment by chenxin-dlut** [comment]
Thank you.
1. In the `README.md` we reported the performance and speed of TransT-N4 and TransT-N2, N2 represents two layers of feature fusion layers.
2. We want to provide a clean baseline, TransT does not need any online update. We have not perform experiments about online update, I think online update can help suppress distractors, an appropriate online update design should improve the performance of TransT.
3. N d-dimensional vectors can be obtained through feature fusion network, N=HW.
    MLP predicts on each vector, a total of HW predictions are obtained.

I don’t know much about mobile applications. Based on my knowledge, I give the following suggestions: (1) FFN can be removed and has little effect on performance. (2) Do more downsampling in backbone, reducing feature size will help speed up. (3) Using N2 version of TransT (4) You can try to remove self-attention and only keep cross-attention (5) The characteristic of TransT is that the bounding box is very accurate, but it may be interfered by similar targets in actual mobile applications. The distractors can be suppressed by designing an online update scheme like DiMP.
