### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by swrdZWJ** [chenxin-dlut/TransT#41]
Thank you for your wonderful work, I have a question about the training datasets. I notice that the trackingnet dataset has a total of 12 [0-11] subsets, why only 4 [0-3] subsets are used for training in the paper？ Thanks ：）

**Comment by chenxin-dlut** [comment]
hello, this is to follow the setting of pytracking. I tried to use [0-11] subsets and found that the performance will improve a bit, about 1 point, so I suggest to use [0-11] subsets.
