### ISSUE TITLE
trackingnet evaluation 

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#44]
您好！
 我在trackingnet官网提交test后的结果进行评估，发现提交的zip文件不符合要求，请问一下您提交的文件如何配置呢？谢谢!

**Comment by chenxin-dlut** [comment]
pysot toolkit中，test.py文件测试之后，打包测试结果上交即可

**Comment by ANdong-star** [comment]
> pysot toolkit中，test.py文件测试之后，打包测试结果上交即可

原来是没有participate to a challenge，已经测出结果了，感谢！
