### ISSUE TITLE
Question in featurefusion_network.py

### ISSUE THREAD

**Issue by LeungWaiHo** [chenxin-dlut/TransT#46]
Dear Chen:

"hs = self.decoder(memory_search, memory_temp,                          tgt_key_padding_mask=mask_search,                          memory_key_padding_mask=mask_temp,                          pos_enc=pos_temp, pos_dec=pos_search)"

I think that the order of input in decoder is firstly memory_temp( i think it is template branch) and secondly memory_search( i think it is search image branch) , because i read your paper I find that k,v of the decode CFA is from above branch and q is from below branch.
Thank you and look forward to your reply.

**Comment by LeungWaiHo** [comment]
我的问题是最后面的CFA输入中k和v应该是来自上面分支的（即template的），q应该是来自下面分支的（即search image的），我感觉好像两个的顺序调转了，不知道是不是有误

**Comment by chenxin-dlut** [comment]
这里没问题的，现在的代码就是search给q，template给k,v。
decoder和encoder的接口是不一样的

**Comment by LeungWaiHo** [comment]
> 这里没问题的，现在的代码就是search给q，template给k,v。
> decoder和encoder的接口是不一样的

现在看是没问题的，谢谢~
