### ISSUE TITLE
About training  time

### ISSUE THREAD

**Issue by swrdZWJ** [chenxin-dlut/TransT#48]
I used the default parameters, batch_size = 38, samples_per_epoch=1000*batch_size, epoch=1000. According to your answer, training on two Nvidia Titan RTX GPUs for 10 days, an average of 100 epochs a day. I used two RTX3090 GPUs and trained for only 45 epochs for a day and a half. I only added os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" to the code.
     os.environ["CUDA_VISIBLE_DEVICES"] = ‘2,3’, what may be the reason for the slow training?
![tensorboard](https://user-images.githubusercontent.com/35293184/121763604-fbb9d380-cb6f-11eb-9c1a-93e88be58b13.png)
  Thanks～

**Comment by chenxin-dlut** [comment]
You can try these:
1. use SSD to load data
2. check the memory and CPU, if several programs are running at the same time(even though use different GPU), they may be slow down because the CPU and memory usage
