### ISSUE TITLE
测评工具

### ISSUE THREAD

**Issue by YRY-NJUPT** [chenxin-dlut/TransT#49]
想问一下文章里是用的什么测评工具呢？比如UAV123文章里给的精度是69.1，我用pysot测试结果是67.9

**Comment by chenxin-dlut** [comment]
uav123我是用got10k toolkit测的，pysot测uav123好像有点bug，每个tracker都会测得低

**Comment by YRY-NJUPT** [comment]
好的谢谢！还有一个问题噢，这个代码如果我训练的过程中断了一次，然后再接着上一个epoch继续训练，会不会对最后的结果有影响？

**Comment by chenxin-dlut** [comment]
每个epoch样本都是随机抽的，无影响的

**Comment by YRY-NJUPT** [comment]
原来如此，谢谢你！
