### ISSUE TITLE
Transt Checkpoint file

### ISSUE THREAD

**Issue by amirhamidihd** [chenxin-dlut/TransT#50]
Hi,

I wanna work on your tracker and train on my own dateset, unfortunately there is no checkpoint file available in your GitHub,
can you upload the checkpoint file?

Obviously, I will cite your paper after getting appropriate results.

**Comment by chenxin-dlut** [comment]
Hello, there are checkpoints.
![IMG_20210622_153451.jpg](https://user-images.githubusercontent.com/56434931/122883072-68eb1700-d36f-11eb-91ee-cc0f3c6acdb9.jpg)

**Comment by amirhamidihd** [comment]
Thanks for your reply but I haven't seen checkpoints file on google cloud and only pretrained model are added, I attach what I seen on the google cloud link
![Screenshot from 2021-06-22 12-08-57](https://user-images.githubusercontent.com/44436361/122884024-f79d6b00-d352-11eb-9802-4604dce6e4f1.png)

**Comment by amirhamidihd** [comment]
Thanks for your reply but I haven't seen checkpoints file on google cloud and only pretrained model are added, I attach what I seen on the google cloud link
![1](https://user-images.githubusercontent.com/44436361/122884162-1ac81a80-d353-11eb-81b9-55d30ee4e435.png)

**Comment by chenxin-dlut** [comment]
These are not the pretrained models. These are the comlete models. 
In another word, it can achieve the performance reported in the paper.

**Comment by amirhamidihd** [comment]
I make the transt.pth as a checkpoint and face with the bellow error 
 File "/home/amir/Documents/TransT/ltr/trainers/base_trainer.py", line 65, in train
    self.load_checkpoint()
  File "/home/amir/Documents/TransT/ltr/trainers/base_trainer.py", line 179, in load_checkpoint
    assert net_type == checkpoint_dict['net_type'], 'Network is not of correct type.'
KeyError: 'net_type'

**Comment by chenxin-dlut** [comment]
if you want to load transt.pth in training, you can do it in this way:
![image](https://user-images.githubusercontent.com/56434931/123051015-e4160100-d433-11eb-815f-99ae3379b5dc.png)
![image](https://user-images.githubusercontent.com/56434931/123051055-ef692c80-d433-11eb-889c-29e90bb1a412.png)

**Comment by amirhamidihd** [comment]
Thanks for your help,

by your help I have solved my issue.
