### ISSUE TITLE
Raw results of TransT trained only on GOT-10k training dataset

### ISSUE THREAD

**Issue by hennnley** [chenxin-dlut/TransT#51]
Hi,

Thank you for your excellent works,
Would you please provide the GOT-10k raw results of TransT trained only on GOT-10k training dataset?

Thanks in advance!

**Comment by chenxin-dlut** [comment]
Hi, you can download it here.
https://pan.baidu.com/s/1LfufdjBGbQ31DpWQpcSZUQ
code: tm68

**Comment by hennnley** [comment]
Thank you!
