### ISSUE TITLE
关于NfS数据集的评估问题

### ISSUE THREAD

**Issue by gufengwei123** [chenxin-dlut/TransT#52]
您好，很荣幸看到您优秀的工作！有问题向您请教，如何用NfS数据集评估模型？具体应该怎么做？，如何处理标注文件？，标注文件包含了一些属性注释，如：0 520 260 564 369 1 0 0 1 "person"，其他数据集groundtruth只有4个值，直接用NfS标注文件的话报错，比如：ValueError: could not convert string to float: '0 520 260 564 369 1 0 0 1 "person"'。期待您的回复，谢谢。

**Comment by chenxin-dlut** [comment]
您好，使用nfs数据集评估的话，直接按照说明用我提供的test.py和eval.py就可以呀，不用管标注的格式

**Comment by Clarkwk** [comment]
> 您好，很荣幸看到您优秀的工作！有问题向您请教，如何用NfS数据集评估模型？具体应该怎么做？，如何处理标注文件？，标注文件包含了一些属性注释，如：0 520 260 564 369 1 0 0 1 "person"，其他数据集groundtruth只有4个值，直接用NfS标注文件的话报错，比如：ValueError: could not convert string to float: '0 520 260 564 369 1 0 0 1 "person"'。期待您的回复，谢谢。

你好，这个问题解决了吗，如果解决了，能提供一下解决方案吗？
