### ISSUE TITLE
关于图像大小的问题

### ISSUE THREAD

**Issue by xl0312** [chenxin-dlut/TransT#53]
您好，很高兴看到您的工作。请问，您对原始训练集里的图像处理成512大小，再加载还是直接加载，后处理成256和128大小再训练

**Comment by chenxin-dlut** [comment]
你好，直接加载再处理

**Comment by chenxin-dlut** [comment]
您好，直接加载再处理

**Comment by xl0312** [comment]
不好意思，再打扰您一下，您的机器多大内存的呢

**Comment by chenxin-dlut** [comment]
64G

**Comment by xl0312** [comment]
好的，谢谢您

**Comment by xl0312** [comment]
您好，再次打扰您一下，我尝试用COCO一个数据集对您的工作进行复现，发现一直加载，直到满64G内存，请问您知道是哪里的问题吗？
发送自 Windows 10 版邮件应用

发件人: chenxin
发送时间: 2021年6月29日 16:36
收件人: chenxin-dlut/TransT
抄送: xl0312; Author
主题: Re: [chenxin-dlut/TransT] 关于图像大小的问题 (#53)

64G

**Comment by chenxin-dlut** [comment]
试一下减少每个epoch的样本数？

**Comment by xl0312** [comment]
我曾经进行过长是，降低到1*batch.size还是这种情况，您单独训练过coco吗？
 
发送自 Windows 10 版邮件应用

发件人: chenxin
发送时间: 2021年6月29日 22:34
收件人: chenxin-dlut/TransT
抄送: xl0312; Comment
主题: Re: [chenxin-dlut/TransT] 关于图像大小的问题 (#53)

试一下减少每个epoch的样本数？

**Comment by chenxin-dlut** [comment]
你好，我没有单独训练过COCO，它毕竟只是一个检测数据集，用于丰富类别，只在COCO上训练恐怕不会取得好的效果。
你有没有试过和其他数据集一起训练有没有这个问题呢

**Comment by xl0312** [comment]
非常抱歉，没有及时回复您，调整work_number后问题已经解决，请问您trackingnet训练集解压后多大呢？

发送自 Windows 10 版邮件应用

发件人: chenxin
发送时间: 2021年7月1日 11:23
收件人: chenxin-dlut/TransT
抄送: xl0312; Comment
主题: Re: [chenxin-dlut/TransT] 关于图像大小的问题 (#53)

你好，我没有单独训练过COCO，它毕竟只是一个检测数据集，用于丰富类别，只在COCO上训练恐怕不会取得好的效果。
你有没有试过和其他数据集一起训练有没有这个问题呢

**Comment by chenxin-dlut** [comment]
如果全都使用的话大概有1.2T左右，不过我只用了前4个包，大概三、四百G

**Comment by xl0312** [comment]
好的，谢谢您，祝您科研工作顺利

发送自 Windows 10 版邮件应用

发件人: chenxin
发送时间: 2021年7月5日 14:19
收件人: chenxin-dlut/TransT
抄送: xl0312; Comment
主题: Re: [chenxin-dlut/TransT] 关于图像大小的问题 (#53)

如果全都使用的话大概有1.2T左右，不过我只用了前4个包，大概三、四百G
