### ISSUE TITLE
Tracking continues even if the person exit the scene

### ISSUE THREAD

**Issue by boza-wd** [chenxin-dlut/TransT#54]
Hi,

thanks for your amazing work!

I am running the inference on some video using your draw rectangle  (Select a ROI and then press SPACE or ENTER button!) and it really does a nice job until the person exits the scene and then the rectangle goes to some random (I assume with the highest score) object nearby, but then it goes back to the person once it re-enters the scene. Is there any threshold which I can set so it does not jump to some random objects/persons for frames when the selected person is not in the scene.

Cheers!

**Comment by chenxin-dlut** [comment]
hello, this is a challenging problemvin tracking field, I give these suggestions.
1. Use the confident score to filter these results, if the tracker has low confidence on its result, discard it.
2. You can train an additional discriminator to determine whether the prediction is the target or not. 
3. If the target often exist the scene, this is more like a long-term tracking problem, which you can solve by looking at some long-term target tracking method, such as GlobalTrack. You can use TransT as a local tracker and combine it with a global tracker.
