### ISSUE TITLE
eval on got-10k

### ISSUE THREAD

**Issue by SilvesterSun** [chenxin-dlut/TransT#55]
作者您好，我想请问下，您是怎么在got-10k上测试的呢？eval.py中没有got-10k的相关代码。

**Comment by chenxin-dlut** [comment]
got10k测指标的话，需要打包测试结果上传到got10k的官网测试

**Comment by SilvesterSun** [comment]
好的，谢谢啦。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 中午11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxin-dlut/TransT] eval on got-10k (#55)





 
got10k测指标的话，需要打包测试结果上传到got10k的官网测试
