### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by JiangWeiHn** [chenxin-dlut/TransT#56]
非常感谢你们的工作！ 我刚学习目标跟踪，想利用此模型训练自己的数据集，需要同时跟踪8个类别。数据集格式是VISDrone 格式,即每个txt文件名称对应一个图片，其内容包含[class_id(starts from 0),track_id(starts from 1), bbox_center_x, bbox_center_y, bbox_width, bbox_height]
请问能训练么?需要怎么修改程序？

**Comment by chenxin-dlut** [comment]
类别可以改一下网络分类的输出数目就可以.
训练的话,需要仿照ltr/dataset/里边LaSOT Got10k等数据集的组织形式写一个类,然后在train_setting文件夹里的transt.py中调用它就可以了.
