### ISSUE TITLE
Lasot的雷达图

### ISSUE THREAD

**Issue by igodogi** [chenxin-dlut/TransT#57]
你好，请问论文里Lasot的雷达图结果是怎么测出来的，Lasot官网没找到attributes相关的标注文件，能否公布个相关代码从参考下呢？感谢

**Comment by igodogi** [comment]
抱歉，解决了。在Lasot评测包里面有。
http://vision.cs.stonybrook.edu/~lasot/toolkit/LaSOT_Evaluation_Toolkit.zip

**Comment by ANdong-star** [comment]
> 抱歉，解决了。在Lasot评测包里面有。
> http://vision.cs.stonybrook.edu/~lasot/toolkit/LaSOT_Evaluation_Toolkit.zip
你好，我在这个包里没看到画雷达图的代码 能画出来很多个单独各个指标的曲线图  雷达图是自己改是吧

**Comment by ANdong-star** [comment]
。

**Comment by ANdong-star** [comment]
。
