### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by Scr-w** [chenxin-dlut/TransT#59]
您好，非常感谢您分享您的工作，请问我在运行pysot_toolkit/test.py文件的时候  ImportError: cannot import name 'region'  是什么原因呢~   期待您的回复   非常感谢~

**Comment by chenxin-dlut** [comment]
这部分是测VOT2019和2018用的,
可以参考这个 https://github.com/STVIR/pysot/blob/master/INSTALL.md 装一下setup.py

其实如果不测vot2019和vot2018的话, 用不到这个东西,可以直接把导入region那一行删掉

**Comment by Scr-w** [comment]
非常感谢您~
