### ISSUE TITLE
Feature Fusion Network输出数据维度

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#60]
您好！ 设置gpu数量1，batchsize=1后，Feature Fusion Network最后一层CFA输出的数据维度是[1，1，1024，256]。看其他transformer的模型有的decoder输出维度为[1,1,1,256]。使用第三维度为1024时发现一次数据运算量巨大会out of memory。请问是否有什么办法可以对第三维度数据进行处理（比如取平均或者一批次一批次的运算）来减少一次的运算量呢？小白求教，谢谢！

**Comment by ANdong-star** [comment]
> 您好！ 设置gpu数量1，batchsize=1后，Feature Fusion Network最后一层CFA输出的数据维度是[1，1，1024，256]。看其他transformer的模型有的decoder输出维度为[1,1,1,256]。使用第三维度为1024时发现一次数据运算量巨大会out of memory。请问是否有什么办法可以对第三维度数据进行处理（比如取平均或者一批次一批次的运算）来减少一次的运算量呢？小白求教，谢谢！

又看了一下是由于其他原因造成爆内存的，现在能跑了。不过1024的维度和其他transformer输出的1的维度会对最终回归或者分类的结果产生较大差异么？

**Comment by chenxin-dlut** [comment]
其他的transformer的输出维度也不是1吧，比如detr里应该是100，这个是代表输出目标的个数

**Comment by ANdong-star** [comment]
> 其他的transformer的输出维度也不是1吧，比如detr里应该是100，这个是代表输出目标的个数

谢谢！考虑到是单目标追踪，最近在尝试修改输出目标的个数改为1。
