### ISSUE TITLE
您好！请问有尝试过在笔记本跑吗？

### ISSUE THREAD

**Issue by sylvia-yhl** [chenxin-dlut/TransT#62]
您好，我在Ubuntu上跑通了，但是暑假在家用不了学校资源，现在想试着用笔记本（win10  RTX 3060）跑，调试一下代码（深度学习刚入门的小白），按照一样的步骤配置了环境，但是总是出错，netwoks文件夹下放的transt.pth和transt_N2.pth没问题的，
![image](https://user-images.githubusercontent.com/65213113/126987865-7f09810e-66ee-475a-a9bc-fd30d58909b7.png)
![image](https://user-images.githubusercontent.com/65213113/126987729-3fd7e4e0-96e2-4a44-916a-ac548ed1b4db.png)

**Comment by chenxin-dlut** [comment]
network要指定到pth文件本身

**Comment by sylvia-yhl** [comment]
感谢回复，不好意思麻烦了，我把路径改成指定.pth了，结果运行后一直卡在这个数据导入界面，没有提示错误，也没有继续运行。请问这个可能是什么原因呢
![image](https://user-images.githubusercontent.com/65213113/127464051-582136e9-a62a-4d45-ae21-7e169a8fe4c0.png)

**Comment by chenxin-dlut** [comment]
这个感觉是运行得比较慢吧，是不是笔记本没有显卡？可以断点debug一下

**Comment by sylvia-yhl** [comment]
好的，谢谢！
