### ISSUE TITLE
关于在ECA,CFA中用到的参数key_padding_mask

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#63]
您好！在代码中看到您设置的attn_mask的值都为None,在encoder的ECA、CFA和decoder的CFA中都设置了key_padding_mask参数，在ECA中key_padding_mask与q值对应，在CFA中key_padding_mask与q值”相反“，想问一下您key_padding_mask这个参数起到了什么作用呢？

**Comment by chenxin-dlut** [comment]
这个参数没用，不指定也一样，是为了拓展性保留的

**Comment by ANdong-star** [comment]
> 这个参数没用，不指定也一样，是为了拓展性保留的

好的非常感谢！意思是我把key_padding_mask全部设置为None也就是False不会对模型造成影响么？

**Comment by chenxin-dlut** [comment]
不会有影响

**Comment by ANdong-star** [comment]
> 这个参数没用，不指定也一样，是为了拓展性保留的

好的非常感谢！
