### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by Junny-han** [chenxin-dlut/TransT#67]
作者您好！请问以下数据集必须全部下载吗
<img width="206" alt="fabb16cbcf270c7b4ed8d297ab6b194" src="https://user-images.githubusercontent.com/54324406/128996569-3670cce4-680b-4eb7-850c-a9949a80435d.png">

**Comment by chenxin-dlut** [comment]
用到哪个下哪个即可

**Comment by Junny-han** [comment]
> 用到哪个下哪个即可

感谢！
