### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by sirius541** [chenxin-dlut/TransT#68]
作者您好，您在github上给出的预训练模型如何加载并继续训练呢。我看您的code里加载的都是checkpoint文件（.pth.tar）。您给的transt.pth怎么加载呢

**Comment by chenxin-dlut** [comment]
hi~这个模型是已经训练好了的，不是用来继续训练的(当然你也可以继续训练，但是需要写代码在训练开始时加载一下这个模型)

**Comment by sirius541** [comment]
我刚才试着在加载checkpoint后又加载您的模型，但是报错了。我目前不确定应该在哪个位置加载这个训练好的模型。还有这个模型在test中可以加载吗，我看了下code，test的时候似乎也是加载的.pth.tar文件吧。顺便说下，您模型的准确率好高~

**Comment by sirius541** [comment]
还有一个问题，您训练到最后的total loss大概是多少呢

**Comment by sirius541** [comment]
好的，感谢！

**Comment by zzzzyq-18** [comment]
> > 我刚才试着在加载checkpoint后又加载您的模型，但是报错了。我目前不确定应该在哪个位置加载这个训练好的模型。还有这个模型在test中可以加载吗，我看了下code，test的时候似乎也是加载的.pth.tar文件吧。顺便说下，您模型的准确率好高~
> 
> 模型在test和train都可以用的，pth.tar和pth对于测试来说都可以。

您好，我想使用您给出的预训练好的trans.pth继续训练，但是加载模型的时候报错了。报错如下：
![a2939250e48ca5a327858a2c8ddfb7b](https://user-images.githubusercontent.com/74850632/227778812-dd2cfb55-6d07-404e-9379-27414ec86c6d.png)
