### ISSUE TITLE
Could you provide Baidu Yun link of the model？

### ISSUE THREAD

**Issue by yangjiangeyjg** [chenxin-dlut/TransT#7]

**Comment by chenxin-dlut** [comment]
链接：https://pan.baidu.com/s/1geI1cIv_AdLUd7qYKWIqzw 
提取码：iiau

**Comment by yangjiangeyjg** [comment]
> 
> 
> 链接：https://pan.baidu.com/s/1geI1cIv_AdLUd7qYKWIqzw
> 提取码：iiau

thanks!
