### ISSUE TITLE
Have you tried different numbers of fusion layers?

### ISSUE THREAD

**Issue by zhouweii234** [chenxin-dlut/TransT#70]
Have you tried different numbers of fusion layers (i.e. `the number of fusion layers = 1,2,3`) ? May I see the results?

**Comment by chenxin-dlut** [comment]
yes，TrsnsT-N2 in ReadMe.md is N=2. The performance of N=3 is similar with 2 and 4. The performance of N=1 is bad, about 5 point drops.
