### ISSUE TITLE
数据维度

### ISSUE THREAD

**Issue by ClimberY** [chenxin-dlut/TransT#74]
请问在特征融合模块中，模板分支与搜索区域分支输入CFA模块的q，k，v的维度分别是多少？融合之后输入CFA模块的q，k，v的维度是多少？

**Comment by chenxin-dlut** [comment]
hi，256

**Comment by ClimberY** [comment]
> hi，256

能具体一些吗，谢:)
搜索区域的特征长度是1024，而模板特征长度是256，那么如何把搜索区域特征的q，和模板特征的k,v统一成一个尺度的？

**Comment by chenxin-dlut** [comment]
可以看一下论文中介绍attention机制的部分
