### ISSUE TITLE
关于网络模型

### ISSUE THREAD

**Issue by yesidooo** [chenxin-dlut/TransT#77]
你好，请问有没有训练好的模型，设备限制自己很难训练---。如有打扰，敬请见谅。

**Comment by chenxin-dlut** [comment]
hi，模型文件readme里有链接的哈

**Comment by yesidooo** [comment]
好的，万分感谢～～

**Comment by yesidooo** [comment]
你好，我加载您的模型权重进行再训练，初始的iou非常低（0.00026），第一个epoch完后也才达到0.00773，请问这是正常的吗？

**Comment by yesidooo** [comment]
好像是我改的代码出现了问题，抱歉打扰了@-@
