### ISSUE TITLE
lasot evalution 雷达图 code

### ISSUE THREAD

**Issue by ANdong-star** [chenxin-dlut/TransT#79]
您好，可否提供一下画“AUC scores of different attributes on the LaSOT dataset”雷达图的代码呢？谢谢。

**Comment by ANdong-star** [comment]
> 您好，可否提供一下画“AUC scores of different attributes on the LaSOT dataset”雷达图的代码呢？谢谢。

可以自己做 但是有个问题 其他对照模型的raw results 或者evalution的结果您是从哪里搞到的呢？

**Comment by chenxin-dlut** [comment]
raw results都可以在tracker的相应的github里找到的

**Comment by hongsheng-Z** [comment]
> > 您好，可否提供一下画“AUC scores of different attributes on the LaSOT dataset”雷达图的代码呢？谢谢。
> 
> 可以自己做 但是有个问题 其他对照模型的raw results 或者evalution的结果您是从哪里搞到的呢？

你好，请问你是怎么能画出来的这个图？

**Comment by hongsheng-Z** [comment]
>你好 你是用matlab做的还是python做的呢
