### ISSUE TITLE
关于测试准确率

### ISSUE THREAD

**Issue by sirius541** [chenxin-dlut/TransT#80]
作者您好，我使用您给的训练好模型利用pysot_toolkit测试了OTB数据集，准确率和论文中的不一样是怎么回事呢

**Comment by chenxin-dlut** [comment]
差多少呢？试试got10k的toolkit看下是否也不一样

**Comment by sirius541** [comment]
我用pysot的toolkit测试otb auc是0.68 论文中是0.69
