### ISSUE TITLE
can i use the TransT for MOT?

### ISSUE THREAD

**Issue by wolinam** [chenxin-dlut/TransT#92]
Now, select one object and track only that, but can I use this for mot?
To do that, which part should I modify?
Thank you!

**Comment by wangdongdut** [comment]
SOT and MOT have different settings and stories. If we speed up TransT by a large margin, I think it may be suitable for MOT when the number of targets is small. But there are some transformer-based MOT methods, such as TrackFormer, MOTR, TransTrack. I guess they are what you what.

**Comment by wangdongdut** [comment]
> Now, select one object and track only that, but can I use this for mot? To do that, which part should I modify? Thank you!

SOT and MOT have different settings and stories. If we speed up TransT by a large margin, I think it may be suitable for MOT when the number of targets is small. But there are some transformer-based MOT methods, such as TrackFormer, MOTR, TransTrack. I guess they are what you what.
