### ISSUE TITLE
Performance on UAV123

### ISSUE THREAD

**Issue by huanmx** [chenxin-dlut/TransT#96]
Hi!
Thank for your great work!

I used the transt.pth model and tested on the UAV123 dataset. I got 66.1 AUC score with pytracking toolkit which is lower than the given raw results(68.1 AUC score). Does this performance normal?

Thank you for your time.

**Comment by chenxin-dlut** [comment]
I didn't test the pytracking toolkit, there might be some difference due to some details. Please try to use the got10k toolkit or pysot toolkit.

**Comment by huanmx** [comment]
> I didn't test the pytracking toolkit, there might be some difference due to some details. Please try to use the got10k toolkit or pysot toolkit.

Actually, I used got10k and pysot toolkit and tested on the UAV123 dataset. I got 70.3 AUC score with got10k toolkit and 68.1 AUC score with pysot toolkit. Does this performance normal?

**Comment by chenxin-dlut** [comment]
yes, I think this is normal, there are some differences between these tools, these differences matter more for small data sets
